### ISSUE TITLE
Add lineageos-18.1 branch

### ISSUE THREAD

**Issue by mimi89999** [samsungexynos7870/android_manifest_samsung_a3y17lte#6]
I can just change the version in revision locally, but for some repos it's not quite clear which branch should be used.

**Comment by FraSharp** [comment]
like what repo?

**Comment by FraSharp** [comment]
ok, added lineage-18.1 manifest in a3y17lte repo

commit: https://github.com/samsungexynos7870/android_manifest_samsung_a3y17lte/commit/1bf6cddfb906dabb9e9eb51968f9a03f306b059a
